### ISSUE TITLE
create docker commit image after task executed

### ISSUE THREAD

**Issue by thaniyarasu** [concourse/docker-image-resource#108]
is it possible to create a image after task's container executed?

let me give detailed explanation.
we can define a task like 

```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.0

inputs:
- name: pipelines

run:
  path: sh
  args:
  - -exc
  - |
     bundle install --gemfile=/app/Gemfile
     blah blah blah
     exit(0)
```

after that is that possible to create a image out of that above container and use that images in consecutive tasks & jobs in the same pipelines
