### ISSUE TITLE
Template variable in repository and insecure_registries is not parsed

### ISSUE THREAD

**Issue by maxromanovsky** [concourse/docker-image-resource#112]
I am receiving the following error when try to use variable in repository:

    failed to unmarshal configStructure: yaml: line 5: did not find expected key

Minimal pipeline:
```yaml
---
resources:
  - name: docker-private-foo
    type: docker-image
    source:
      repository: "{{hostname}}:8083/foo"
      insecure_registries:
        - "{{hostname}}:8083"
```

Fly command line:

    fly -t local set-pipeline --pipeline docker --config docker.yml --var="hostname=localhost"

If variable in `repository` is removed, I receive a different error:

    failed to unmarshal configStructure: yaml: line 7: did not find expected '-' indicator

**Comment by maxromanovsky** [comment]
As explained in http://stackoverflow.com/questions/43158685/how-to-use-yaml-template-variable-as-a-part-of-value-in-concourse-ci, this is currently unsupported

**Comment by siredmar** [comment]
Sorry, to "reopen" that issue. Has there been any progress on this topic?
I am trying to use a variable as repository in docker-image e.g.
```
...
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker_image))
    tag: git
...
```
