### ISSUE TITLE
not able to use JFrog Artifactory for docker-image-resource

### ISSUE THREAD

**Issue by androyamamoto** [concourse/docker-image-resource#118]
Hi,
we manage our docker-images in our private JFrog Artifactory. Now we want to use these images for image-resource in our concourse pipeline.

But if we config and run the following test-task:

```
platform: linux
image_resource:
  type: docker-image
  source:
    repository: <HOST>:<PORT>/cf/cli
    tag: "latest"
    insecure_registries: [ "<HOST>:<PORT>"]
run:
  path: bash
```

We get the following failure:

```
bash$ fly -t main  execute -c task.yml
executing build 37
initializing
no versions of image available
errored
```

Kind regards,
André
