### ISSUE TITLE
ECR Base IMAGE in Dockerfile fails to authenticate

### ISSUE THREAD

**Issue by richarddowner** [concourse/docker-image-resource#120]
Hi all, Im having authentication issues when pulling a base docker image from AWS ECR in the concourse pipeline. Getting this error:
```
waiting for docker to come up...
waiting for docker to come up...
Sending build context to Docker daemon  25.7 MB
Step 1/6 : FROM xxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/myimage-base:latest
Pulling repository xxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/myimage-base
unauthorized: authentication required
```
The resource uses `myimage`
```
resources:
- name: web-api
  type: docker-image
  source:
    repository: xxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/myimage
    aws_access_key_id: {{aws_access_key_id}}
    aws_secret_access_key: {{aws_secret_access_key}}
```
The `myimage` Docker file uses `FROM xxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/myimage-base:latest`

This only happens when the Dockerfile uses `FROM xxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/myimage-base:latest`
Can confirm that any public image works, ie. `FROM microsoft/dotnet:1.1.1-sdk`

I think it might have something to do with ECR requiring `aws ecr get-login --no-include-email --region ap-southeast-2`
