### ISSUE TITLE
load_cache or similar support

### ISSUE THREAD

**Issue by matiasanaya** [concourse/docker-image-resource#121]
I want to know if it's possible to use a `get` resource instead of pulling down the image when `cache: true` is set for building.

Say this is my current job (which has the nice benefit that the `FROM` image can be cached by `concourse`):

```
- get: repo
- get: a-cached-docker-image-from
  params: { save: true }
- put: a-docker-image
      get_params: { skip_download: true }
      params:
        build: repo
        cache: true
        cache_tag: a-cached-tag
        load_base: a-cached-docker-image-from
```

I'd like for something like the following to work equivalently (where the `cache` image can be cached by `concourse`):

```
- get: repo
- get: a-cached-docker-image
  params: { save: true }
- get: a-cached-docker-image-from
  params: { save: true }
- put: a-docker-image
      get_params: { skip_download: true }
      params:
        build: repo
        load_cache: a-cached-docker-image # this does not exist
        load_base: a-cached-docker-image-from
```
