### ISSUE TITLE
Docker PUT always downloads image even if digest is same

### ISSUE THREAD

**Issue by richarddowner** [concourse/docker-image-resource#123]
## **Docker PUT always downloads image even if digest is same**
* This adds considerable time to builds with multiple images 
* Is this a bug or am I missing a config step?
```
resources:
- name: web-api
  type: docker-image
  source:
    repository: xxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/myproject-webapi
    aws_access_key_id: {{aws_access_key_id}}
    aws_secret_access_key: {{aws_secret_access_key}}
```
...
```
 - put: web-api
    params:
      build: bin/MyProject.WebAPI
      tag: version/version
    get_params:
      skip_download: true
```

### Two different builds pulling new image with same SHA
**#287**
![digest1](https://user-images.githubusercontent.com/5424527/26955717-aa2511f0-4d0c-11e7-9832-494ea79d2732.PNG)
**#288**
![digest2](https://user-images.githubusercontent.com/5424527/26955719-adae2082-4d0c-11e7-9804-f6073eb58bda.PNG)
