### ISSUE TITLE
Can't find tag file

### ISSUE THREAD

**Issue by nbijl-worthit** [concourse/docker-image-resource#135]
Hi 
i'm trying to push images to a docker repo with a specific tag (base on the git-rev) but somehow my tag file is not found.
The configuration: 
```yaml
- name: api-build
  build_logs_to_retain: 10
  plan:
  - get: git-repo
    params: {depth: 1}
    trigger: true
  - task: write-git-rev
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine/git
      inputs:
        - name: git-repo
      run:
        dir: git-repo
        path: sh
        args:
          - -exc
          - |
            git rev-parse --short HEAD > ../git_rev
            cd ..
            pwd
            ls -alh
            cat git_rev
  - put: docker-api-image
    params:
      tag: git_rev
      build: git-repo/api/
```
I just want to write the git rev to a file, then push the image with a tag to the docker repo. 
This way I can deploy a certain version of the docker repo to a temp server, to run our end-to-end (acceptance) tests against.

I must be doing something stupid but can't get it to work somehow..

**Comment by nbijl-worthit** [comment]
Ahhh I did not define a output. 
This works: 


```yaml
- name: api-build
  build_logs_to_retain: 10
  plan:
  - get: git-repo
    params: {depth: 1}
    trigger: true
  - task: write-git-rev
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine/git
      inputs:
        - name: git-repo
      outputs:
        - name: tags
      run:
        dir: git-repo
        path: sh
        args:
          - -exc
          - |
            git rev-parse --short HEAD > ../tags/git_rev
  - put: docker-api-image
    params:
      tag: tags/git_rev
      build: git-repo/api/
```
