### ISSUE TITLE
Is "COPY" within the Dockerfile allowed?

### ISSUE THREAD

**Issue by laugimethods** [concourse/docker-image-resource#139]
Hi,
Is it possible to use build a Docker Image from a Dockerfile that contains a "COPY" (which makes reference to a complementary resource)?

`pipeline.xml`:
```yaml
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-org
    trigger: true
  - get: standalone_ear
    trigger: true
  - task: standalone_ear_input ### ONLY FOR DEBUG
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      inputs:
      - name: standalone_ear
      run:
        path: sh
        args:
        - -exc
        - |
          pwd
          ls -la .
  - put: docker-image
    params:
      build: git-org
```

`Dockerfile`:
```shell
FROM xxx:latest

COPY . /tmp
RUN ls -als /tmp

COPY ./standalone_ear/ /tmp
```

Outcome:
```shell
>_ standalone_ear_input
+ pwd
/tmp/build/2ad3958d
+ ls -la .
total 12
drwxr-xr-x 3 root root 4096 Aug 25 13:42 .
drwxr-xr-x 3 root root 4096 Aug 25 13:42 ..
drwxr-xr-x 1 root root 4096 Aug 25 13:42 standalone_ear

>_docker-image
Step 2/4 : COPY . /tmp
 ---> b0a51de26bc4
Removing intermediate container a0f6aef09596
Step 3/4 : RUN ls -als /tmp
 ---> Running in 096ec8f699b5
total 44
4 drwxrwxrwt  8 root root 4096 Aug 25 13:43 .
4 drwxr-xr-x 30 root root 4096 Aug 25 13:43 ..
4 drwxrwxrwt  2 root root 4096 Aug  1 17:23 .ICE-unix
4 drwxrwxrwt  2 root root 4096 Aug  1 17:23 .Test-unix
4 drwxrwxrwt  2 root root 4096 Aug  1 17:23 .X11-unix
4 drwxrwxrwt  2 root root 4096 Aug  1 17:23 .XIM-unix
4 drwxrwxrwt  2 root root 4096 Aug  1 17:23 .font-unix
4 drwxr-xr-x  9 root root 4096 Aug 25 13:42 .git
4 -rw-r--r--  1 root root   84 Aug 25 13:42 Dockerfile
4 -rw-r--r--  1 root root   44 Aug 25 13:42 README.md
4 -rwx------  1 root root  836 Aug  1 17:24 ks-script-ffclxw
0 -rw-------  1 root root    0 Aug  1 17:23 yum.log
Step 4/4 : COPY ./standalone_ear/ /tmp
lstat standalone_ear/: no such file or directory
```
