### ISSUE TITLE
tag_as_latest doesn't work

### ISSUE THREAD

**Issue by nsitbon** [concourse/docker-image-resource#140]
Hi

Using Concourse 3.3.3 I can't make tag_as_latest working as expected. Even with previous version it doesn't tag the image as latest.

Nothing special in my configuration file:
```yml
- put: prod-image
  params:
      load: prod-image
       tag: prod-helm/version
       tag_as_latest: true
```

I tried to rebuild the docker image of your resource but it's not easy as it's supposed to be integrated into your pipeline.

Any ideas?

**Comment by jtarchie** [comment]
Please specify how it is not working.

* Did any image get pushed up?
* What tags were pushed?
* etc.

**Comment by nsitbon** [comment]
Sorry only the tag specified in the file _prod-helm/version_ has been pushed but I never get the latest tag. I tried multiple conbination with and without the tag directive. I also tried different way to get the _true_ value like `tag_as_latest: TRUE` or `1` etc.

**Comment by simondiep** [comment]
I'm running into issue as well

**Comment by holyjak** [comment]
Same problem here, using Concourse 4.2.2, having: 

```yaml
resources:
  - name: web-image
    type: docker-image
    source:
      repository: 12345.dkr.ecr.eu-west-1.amazonaws.com/myapp
      <<: *aws-credentials
# ...
jobs:
- name: build-main
  plan:
  # ...
  - aggregate:
  - put: web-image
      resource: web-image
      params:
        build: build/docker
        skip_download: false
        tag_file: version/number
        tag_prefix: next_
        tag_as_latest: true
      get_params: { skip_download: true }  
``` 

The image is only tagged with something like `next_0.0.5`. Log from the relevant part of the build:

```
waiting for docker to come up...
Sending build context to Docker daemon  210.7MB
Step 1/10 : FROM openjdk:8-jre-alpine
8-jre-alpine: Pulling from library/openjdk
...
Successfully built d184095cdaa1
Successfully tagged 12345.dkr.ecr.eu-west-1.amazonaws.com/myapp:next_0.0.5
The push refers to repository [12345.dkr.ecr.eu-west-1.amazonaws.com/myapp]
...
510f10602166: Pushed
next_0.0.5: digest: sha256:f6877b9770544d61f19b8d6548127a0100a278bdc6b4c1b299b980551628f381 size: 2415
```
