### ISSUE TITLE
Multi stages build cache work only with last stage

### ISSUE THREAD

**Issue by kwladyka** [concourse/docker-image-resource#148]
Dockerfile
```
FROM clojure:lein-alpine as dependencies
WORKDIR /app
COPY project.clj .
RUN lein deps

FROM dependencies
WORKDIR /app
RUN lein test

FROM dependencies as builder
WORKDIR /app
RUN lein uberjar

FROM anapsix/alpine-java
EXPOSE 8080
WORKDIR /app
COPY --from=builder /app/target/*-standalone.jar ./app.jar
CMD ["java", "-cp", "/app/app.jar", "clojure.main", "-m", "etingroup.core"]
```

It looks like only this part (last step) is cached:
```
FROM anapsix/alpine-java
EXPOSE 8080
WORKDIR /app
COPY --from=builder /app/target/*-standalone.jar ./app.jar
CMD ["java", "-cp", "/app/app.jar", "clojure.main", "-m", "etingroup.core"]
```

Is it possible to improve?

**Comment by chrishiestand** [comment]
This should now be possible with `cache_from`. The complication is that you have to save each intermediate image (everything up until the new `FROM`) as its own image, and include that image in the `cache_from` array. This is a docker limitation afaik.

**Comment by zivori** [comment]
I see the base image cached locally as <none> : <none> but how can I tag this to push it to remote registery (so it can be used in the future for caching)
`
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
<none>                           <none>              7dbdf83dd6a0        8 seconds ago       690MB
node                             10.1.0-alpine       1c517a20b2fd        8 weeks ago         71MB
`

**Comment by kwladyka** [comment]
BTW There is connected topic to this issue
https://github.com/docker/cli/issues/666

**Comment by chrishiestand** [comment]
@zivori something like this should work:

```bash
docker tag 7dbdf83dd6a0 my-intermediate-image:latest
docker push my-intermediate-image:latest
```

**Comment by dhinus** [comment]
This is a full example of how I am doing multi-stage builds using `cache_from`, hope it helps. Please note I am also using `load_bases` to make sure the base image (`node:8-alpine` in my case) is cached.

```
resources:
  - name: node
    type: docker-image
    source:    
      repository: node
      tag: "8-alpine"

  - name: docker-app
    type: docker-image
    source:
      repository: my/app
  
  - name: docker-app-stage1
    type: docker-image
    source:
      repository: my/app
      tag: stage1-latest
    
jobs:
- name: build
  plan:
    - get: docker-app
      params:
        save: true
    - get: docker-app-stage1
      params:
        save: true

    - put: docker-app-stage1
      params:
        build: app
        target_name: stage1
        load_bases:
          - node
        cache_from:
          - docker-app-stage1
      get_params:
        save: true

    - put: docker-app
      params:
        build: app
        load_bases:
          - node
        cache_from:
          - docker-app
          - docker-app-stage1
      get_params:
        skip_download: true
```
