### ISSUE TITLE
Use docker image resource as task input

### ISSUE THREAD

**Issue by encron** [concourse/docker-image-resource#152]
Not sure how to classify this but I am facing an issue where I am unable to use my Docker image resource as the input of a task.

In my pipeline, I have currently two jobs: "build-it" and "test-it":
"build-it" will get triggered on a git commit, start a Docker build and eventually push that image to the registry. 
"test-it" will get triggered by the newly created Docker image. It is here that I want to use that image as input to run unit-tests.

Basically it looks like this:
```
---
resources:
- name: git-repo
  type: git
  source:
    uri: git@github.com:myorg/my-repo.git
    branch: master
    private_key: {{github-private-key}}

- name: docker-image
  type: docker-image
  source:
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: myorg/something

jobs:
- name: build-it!
  serial: true
  plan:
  - get: git-repo
    trigger: true
  - put: docker-image
    params:
      build: git-repo
      tag: sometag
- name: test-it!
   serial: true
   plan:
   - get: docker-image
      trigger: true
      passed: [build-it!]
   - task: unit-test
      config:
        platform: linux
        inputs:
          - name: docker-image
        run:
          path: npm
          args:
          - run test
```
Everything works until I get to the test job where I get this error:

```
initializing
volume graph is disabled
errored
```
I suspect this vague message means that it is not running my task in my Docker image as it should.

I don't really find any examples or documentation on how to pass this Docker image resource as an input for a task. So if I am simply doing something wrong, please do tell!

**UPDATE**

At the moment I worked around this issue by doing the testing with a default node image using the git repo as resource. Although ideally I wouldn't want to pull in another image and do `npm install` there too, I just want to re-use my built image which already contains the required node modules. This feels like a lot of waste to do something simple :/
