### ISSUE TITLE
Unable to use ECR repository: no basic auth credentials

### ISSUE THREAD

**Issue by cjohansen** [concourse/docker-image-resource#161]
```yml
- name: my-docker-image
  type: docker-image
  source:
    repository: MY_ACCOUNT.dkr.ecr.eu-west-1.amazonaws.com/MY_REPO
    tag: d196e5688d
    aws_access_key_id: ((docker-aws-access-key-id))
    aws_secrey_access_key: ((docker-aws-secret-access-key))
```

I am unable to make this resource work. I've verified that the provided credentials can pull the image using:

```sh
$(aws ecr get-login --no-include-email --profile concourse --region eu-west-1)
```

The Docker resource fails with:

```
failed to fetch manifest: Get https://MY_ACCOUNT.dkr.ecr.eu-west-1.amazonaws.com/v2/MY_REPO/manifests/d196e5688d: no basic auth credentials
```

I even tried to echo the configuration to `/opt/resource/check` locally in a container hoping to get some more details, but I have little to go on. Am I using it wrong?
