### ISSUE TITLE
ECR pull fails when build ARG is used in FROM statement for base image

### ISSUE THREAD

**Issue by PeteGoo** [concourse/docker-image-resource#162]
If the base image is passed in via an ARG then the regex match will not recognise that it needs to login to ECR.

e.g.
```Dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE:-my-other-base:latest}
...
```

```yaml
put: my-ecr
      params:
        build: source
        build_args_file: previous/build_args.json
```

```bash
Sending build context to Docker daemon  5.632kB
Step 1/3 : ARG BASE_IMAGE
 ---> 
Step 2/3 : FROM ${BASE_IMAGE:-my-other-base:latest}
Get https://<account-id>.dkr.ecr.us-west-2.amazonaws.com/v2/my-other-base/manifests/sha256:<sha256>: no basic auth credentials
```

Not sure how to resolve this one. Perhaps also take build_args into account when deciding whether to ECR login? This would also fail if the ARG had a fallback though. 

Would there be any harm in logging in if we see the ECR pattern anywhere in the Dockerfile or args file? It sucks but I can't think of a better way right now.
