### ISSUE TITLE
running a task inside this resource image: privilege required?

### ISSUE THREAD

**Issue by rosenhouse** [concourse/docker-image-resource#164]
## background
I'm trying to get `tag_filter`-like behavior out of a `docker-image-resource`.

An external CI system builds commits from a [git repo](https://github.com/envoyproxy/envoy) and for each successful build, it pushes a docker image to a [docker repo](https://hub.docker.com/r/envoyproxy/envoy/).  The docker image gets tagged with the git commit SHA.  If the git commit had a semver tag, then the docker image gets that also.

I want to consume the docker images, but only the semver-tagged ones.  I didn't see a `tag_filter` config on the resource, so I tried to run `docker pull` in a task.

## a task running inside this resource image

  ```yaml
  - task: pull-envoy-image
    privileged: true  # but why?
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/docker-image-resource
      params:
        DOCKER_REPO: envoyproxy/envoy
      inputs:
      - name: envoy-source
      outputs:
      - name: image
      run:
        path: bash
        args:
        - -eux
        - -c
        - |
          set -o pipefail
          TAG="$(cat envoy-source/.git/ref)"
          SRC=" \"source\": { \"repository\": \"${DOCKER_REPO}\", \"tag\": \"${TAG}\" } "
          VER="$(echo "{ $SRC }" | /opt/resource/check | jq .[0])"
          echo "{ $SRC , \"version\": $VER }" | /opt/resource/in $PWD/image
          ls -la $PWD/image/rootfs/usr/local/bin/envoy
  ```

This works.

But without the `privileged: true`, the `/opt/resource/in` line errors with

```
mount: permission denied (are you root?)
```

Why does the resource itself work fine without privilege, but if I try to use the image for a task, then I need it?
