### ISSUE TITLE
mount: permission denied (are you root?)

### ISSUE THREAD

**Issue by myles-mcdonnell** [concourse/docker-image-resource#169]
I have the above issue which I have [posted on SO](https://stackoverflow.com/questions/48327705/concourseci-docker-image-resource-issue-mount-permission-denied-are-you-roo).  

I notice this error has cropped up in the context of ECR but I only want to use a public image.

Thx

**Comment by vito** [comment]
This was answered on SO. In the future, please don't replicate StackOverflow questions here. :) We have enough issues to wrangle as it is!

**Comment by Sispheor** [comment]
For those who pass here, here is the solution (add privileged: true)
```yml
resource_types:
  - name: docker-image-resource
    privileged: true
    type: docker-image
    source:
      repository: concourse/docker-image-resource
      tag: latest
```
