### ISSUE TITLE
Tag and Publish versions of concourse/docker-image-resource

### ISSUE THREAD

**Issue by jamespamplin** [concourse/docker-image-resource#178]
We've been using custom resources from this repo to use some of the features in master that are not currently available in the built in `docker-image` resource in our concourse version (3.6).

We're using it as follows:
```yaml
resources:
  - name: docker-gateway
    type: docker-image-upstream
    source:
      ...
resource_types:
  - name: docker-image-upstream
    type: docker-image
    source:
      repository: concourse/docker-image-resource
      tag: latest
    privileged: true
```

Recently, we were hit with an issue in `master` / `latest` builds which were breaking our jobs. (for reference this was #174).

Ideally, I'd rather couple our builds to a tagged/versioned build that is static and stable (eg: 1.0, 1.1, etc). Is it possible to have tagged releases of this repo in both the codebase and published to dockerhub? Thanks!
