### ISSUE TITLE
How to bind the socket through the .yml file..!?

### ISSUE THREAD

**Issue by rohithmn3** [concourse/docker-image-resource#182]
Hi Team,

My pipeline.yml file looks below, where i am trying to install docker and run `docker pull` inside the ubuntu container which concourse created.
FYI...
```
---
resources:
- name: hello_hapi
  type: git
  source:
    uri: https://<username>:<password>@github.com/rohithmn3/hello_hapi.git
    branch: master

platform: linux

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: hello_hapi
    trigger: true
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          volumes: /var/run/docker.sock:/var/run/docker.sock
          privileged: true
      inputs:
        - name: hello_hapi
      outputs:
        - name: update_times
      run:
        path: hello_hapi/task_show_uname.sh
```
I have kept the code in github public repo : https://github.com/rohithmn3/hello_hapi/blob/master/task_show_uname.sh

When i run the concourse pipeline, it FAILS - as it couldn't able to run `docker images` command post docker installation.
Below is the Error/Exception:
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I am getting above error/exception because, i couldn't able to bind socket while docker build. 
Help me here...!?

Regards,
Rohith
