### ISSUE TITLE
additional_tags not working

### ISSUE THREAD

**Issue by jaychris** [concourse/docker-image-resource#183]
Attempting to use the `additional_tags` parameter when building/pushing an image.  Here's the task:

```
- put: deployable-image
      params:
        build: code/
        dockerfile: code/infrastructure/dockerfiles/myApp/Dockerfile
        tag: assets/version
        additional_tags: assets/tags
```
and here's the resource for `deployable-image`:

```
- name: deployable-image
  type: docker-image
  source:
    repository: registry.service.nsi.gemini/gemini/myApp
    username: concourse
    password: {{concourse-registry-password}}
    ca_certs:
      - domain: registry.service.nsi.gemini
        cert: {{gemini-ca-cert}}
```

Where `assets/tags` is a file that contains a single line of space-delimited tags that should be added to the image.

Not sure how to debug this - I can step into the build step and see both the version file `assets/version` and the additional tags file `assets/tags` exists, but the image is only being pushed with the single tag pulled from `assets/version`.
