### ISSUE TITLE
Source does not support specifying image digest

### ISSUE THREAD

**Issue by phillbaker** [concourse/docker-image-resource#187]
The docker image resource supports pulling images by tag. The [docker commandline](https://docs.docker.com/engine/reference/commandline/pull/) supports pulling images by tag and digest.

Would a pull request to add `digest` to the [source configuration](https://github.com/concourse/docker-image-resource#source-configuration) be accepted?

Original description:
----
This may be an issue with how concourse itself works, if so, maybe this is a documentation issue.

The ~~docker image resource supports pulling images by tag and digest~~. If an image is specified by tag initially, and then the configuration is updated to specify a previously pulled digest, the most recent version of the docker image is used. 

Example:
```
# original specification
- resources:
  - name: ansible
    type: docker-image
    source:
      repository: williamyeh/ansible
      tag: ubuntu16.04
```

Updated to:
```
- resources:
  - name: ansible
    type: docker-image
    source:
      repository: williamyeh/ansible
      digest: sha256:fad6172150bfd446bae9948b6fcec2fff95368448690fc3d807904f9ce24a272 # previous version of the `ubuntu16.04` tag, ubuntu16.04 now resolves to a different digest
```

Tasks resolve to using image `c14d84964da7ff870c9daf184f9d130919abb6de44f62fb54e68f26bbc71a7e1`.

A workaround is to turn off more recent versions of resource:
![screen shot 2018-03-28 at 10 15 32 pm](https://user-images.githubusercontent.com/94505/38066511-4a0766a0-32d6-11e8-9b72-4402259af36d.png)

I believe that specifying the earlier pulled digest is treated as "already pulled" by the resource check, but then treated as an "older version" by concourse since there are newer resource versions. 

One possible fix may be to add a hash of the specification parameters into the version metadata of this resource so that changing the specification parameters forces a new concourse resource version, here:

https://github.com/concourse/docker-image-resource/blob/380a4ca0fad939715a30a18c60160598fd5b1faf/assets/in#L97-L104

I'm happy to contribute a PR if that makes sense.

Edit: I suppose changing the resource name would also work.
