### ISSUE TITLE
Support pushing both `latest` and a specific version tag in a single `put`

### ISSUE THREAD

**Issue by moredip** [concourse/docker-image-resource#19]
It would be handy to be able to push multiple tags with one `put`. My specific use case is pushing a version tag and a latest tag.

At the moment I am doing this, which seems to be quite inefficient:

``` yaml
 - do:
   - put: docker-image-latest
     resource: docker-image
     params:
       build: package
   - put: docker-image-versioned
     resource: docker-image
     params:
       tag_prefix: v
       tag: version/number
       build: package
```

The main use case I can see for this is pushing a `latest` and a specific version, which could perhaps be configured with an extra resource param. Something like this?

``` yaml
   - put: docker-image
     params:
       tag_prefix: v
       tag: version/number
       also_tag_latest: true
       build: package
```
