### ISSUE TITLE
tasks' docker_image not being pulled 

### ISSUE THREAD

**Issue by pfijalki** [concourse/docker-image-resource#191]
I've setup task  with config like

```
task: echo-task
config:
 platform: linux
 image_resources:
   type: docker-image
   source: 
      repository: my.repo/echo-image
      tag: latest
```

and after updating image repo on my.repo docker repository new image is not being pulled, how so ?
