### ISSUE TITLE
skip_download not working

### ISSUE THREAD

**Issue by fewknow** [concourse/docker-image-resource#196]
Here is my pipeline code:
on_success:
          put: ecr-((CONTAINER_IMAGE))
          params:
            build: code_build
            input: code_build
            tag: code_build/commit.txt
            skip_download: true

I don't want to download the container on this `put` call. 

<img width="1138" alt="screen shot 2018-05-02 at 12 13 50 am" src="https://user-images.githubusercontent.com/22297806/39505056-f8114112-4d9d-11e8-835b-42269abca0e6.png">

As you can see in the screen shot once the image is pushed to repository it is downloaded.

**Comment by pn-santos** [comment]
when using it in a `put` you need to do it like this:
```
put: ...
get_params: { skip_download: true }
```

**Comment by fewknow** [comment]
should this work? 
```  - task: build-java-spring-artifact
      privileged: true
      image: resource-build-java
      params:
        ARTIFACTORYPASSWORD: ((ARTIFACTORYPASSWORD))
        REPOSITORY_NAME: ((CONTAINER_IMAGE))
        SERVICE_NAME: ((SERVICE_NAME))
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        TYPE: ((BUILD_TYPE))
        LOGLEVEL: ((LOGLEVEL))
        SKIP_TEST: ((SKIP_TEST))
      file: resource-devops.ci/tasks/task_build_test_store.yml
      on_success:
        put: git-commit
        params:
          file: code_build/commit.txt
        on_success:
          put: ecr-((CONTAINER_IMAGE))
          params:
            build: code_build
            input: code_build
            tag: code_build/commit.txt
          get_params: { skip_download: true }```

**Comment by vito** [comment]
Yep, that goes in `get_params`, not `params`.

**Comment by fewknow** [comment]
@vito This still doesn't seem to work.  I have updated to `get_params` and it still is downloading. 

![screen shot 2018-07-06 at 11 11 46 am](https://user-images.githubusercontent.com/22297806/42386407-6a8939aa-810d-11e8-93cf-4b5d41690147.png)

my pipeline code 
```
- name: Deploy container to Sandbox
  on_success: *success-alert
  on_failure: *failure-alert
  public: true
  plan:
    - aggregate:
      - get: git-commit
      - get: resource-devops.ci
      - get: Terraform Deploy
      - get: DEV
      - get: ecr-((CONTAINER_IMAGE))
        trigger: true
        get_params: { skip_download: true}
    - task: terraform-deploy-to-sand
      privileged: true
      image: Terraform Deploy
      file: resource-devops.ci/tasks/terraform_deploy.yml
      input_mapping: {CODE: DEV}
      params:
        TERRAFORM_ENV: sand
        TERRAFORM_PROJECT: ((TERRAFORM_PROJECT))
        CONTAINER_IMAGE: ((CONTAINER_IMAGE))
        TERRAFORM_VERSION: ((TERRAFORM_VERSION))
        SERVICE_NAME: ((SERVICE_NAME))
        MGMT_AWS_SECRET_ACCESS_KEY: ((MGMT_AWS_SECRET_ACCESS_KEY))
        MGMT_AWS_ACCESS_KEY_ID: ((MGMT_AWS_ACCESS_KEY_ID))
        ENV_AWS_SECRET_ACCESS_KEY: ((DEV_AWS_SECRET_ACCESS_KEY))
        ENV_AWS_ACCESS_KEY_ID: ((DEV_AWS_ACCESS_KEY_ID))
        GIT_USERNAME: ((bitbucket-user))
        GIT_PASSWORD: ((bitbucket-password))
        VAULT_TOKEN: ((VAULT_TOKEN))
```
