### ISSUE TITLE
`cache_from` parameter does not work

### ISSUE THREAD

**Issue by jacob-hd** [concourse/docker-image-resource#200]
When using `cache_from` and providing a docker image with layers that do not need to be re-built, Concourse will re-build all of the layers every time.

Here is an example pipeline:
```yaml
---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pull-request
  type: pull-request
  source:
    repo: quotecenter/app-thunder-storefront
    access_token: ((github-token))
    username: x-oauth-basic
    password: ((github-token))

- name: docker-image
  type: docker-image
  source:
    repository: gcr.io/np-quotecenter/app-thunder-storefront/pull-requests
    username: _json_key
    password: ((gcr-key))

- name: docker-image-master
  type: docker-image
  source:
    repository: gcr.io/np-quotecenter/app-thunder-storefront/master
    username: _json_key
    password: ((gcr-key))
    tag: latest

jobs:
- name: build
  plan:
  - aggregate:
    - get: app-thunder-storefront
      resource: pull-request
      trigger: true
      version: every

    - get: docker-image-master
      params:
        save: true

  - put: github-status-build
    params:
      commit: app-thunder-storefront/.git/head_sha
      state: pending

  - put: docker-image
    params:
      build: app-thunder-storefront
      build_args:
        NPM_TOKEN: ((myget-token))
      tag: app-thunder-storefront/.git/head_sha
      cache_from: [ docker-image-master ]
```

The docker image `docker-image-master` contains the exact same docker image that this PR is building - I have verified this several times.

The resulting output shows that it builds the entire image from scratch without using any caching:
![image](https://user-images.githubusercontent.com/31864739/40672074-91067e02-6322-11e8-8ca7-fea3bd9c2407.png)
