### ISSUE TITLE
semver resource not usable as build_arg

### ISSUE THREAD

**Issue by donkeybanana** [concourse/docker-image-resource#203]
It looks like use of the [semver resource](https://github.com/concourse/semver-resource) is not compatible with this resource's `build_args`. It is however perfectly usable as a `tag`.

# Configuration

## Pipeline task
```
...
    - put: rpm-linux-x64-el6
      params:
        cache: true
        cache_tag: latest
        build: source
        build_args:
          CENTOS_RELEASE: 6
          REGISTRY: ((docker-registry))
          VERSION: version/number
        dockerfile: source/Dockerfile-linux-x64
        load_base: rpm-el6
        tag: version/number
        tag_as_latest: true
...
```

## Dockerfile
```
ARG CENTOS_RELEASE
ARG VERSION
ARG REGISTRY

FROM $REGISTRY/myrepo/rpm-el$CENTOS_RELEASE:$VERSION
```

# Result

```Sending build context to Docker daemon  25.96MB
Step 1/17 : ARG CENTOS_RELEASE
Step 2/17 : ARG VERSION
Step 3/17 : ARG REGISTRY
Step 4/17 : FROM $REGISTRY/myrepo/rpm-el$CENTOS_RELEASE:$VERSION
invalid reference format
```

This result can also be reproduced by omitting the `VERSION` arg when invoking `docker build` locally:

```
❯       docker build \
                --build-arg CENTOS_RELEASE=6 \
                --build-arg REGISTRY=whoop \
                -t test \
                -f Dockerfile-linux-x64 \
                .

Sending build context to Docker daemon  25.96MB
Step 1/17 : ARG CENTOS_RELEASE
Step 2/17 : ARG VERSION
Step 3/17 : ARG REGISTRY
Step 4/17 : FROM $REGISTRY/myrepo/rpm-el$CENTOS_RELEASE:$VERSION
invalid reference format
```

# Debugging the job

## `version/number`

As shown here, `version/number` is indeed set (we already established this above, as previous jobs are able to tag using the semver resource), checked using `fly hijack`:

```
bash-4.4# cat version/number
4.0.0-rc.1
```
