### ISSUE TITLE
ECR Support with Concourse v3.8.0

### ISSUE THREAD

**Issue by manali14** [concourse/docker-image-resource#210]
We are building a Docker Image from a Private ECR Image and passing that as load_base image. But we end up getting the following error:

`Get https://<ECR_URL>/manifests/latest: no basic auth credentials`

The Url is appended with https and a remote call is made instead of fetching from local. The above works fine in case we use cache true as described here : https://github.com/concourse/docker-image-resource/issues/101#issuecomment-312529473

The CI Pipeline is described as:

```
   plan: 
    - aggregate:
      - get: ecr-web
        params:
          save: true
    - put: ecr-api
      params:
        load_base: ecr-web
        build: ((path_to_docker_file))
        tag_as_latest: true
```

Here, `ecr-api` and `ecr_web` are ECR Resources.
