### ISSUE TITLE
build should continue if resource cache is not available

### ISSUE THREAD

**Issue by chrishiestand** [concourse/docker-image-resource#222]
It seems reasonable that, by default, unavailable cache should not stop a build. Unfortunately the build hangs because the cached image is not available and concourse does not know it is an optional resource. This is operationally burdensome because it means the first time you run some pipelines you must setup the configuration without cache, build and push, then modify the pipeline to add cache.

![image](https://user-images.githubusercontent.com/100825/42850500-cfba23fc-89dc-11e8-9c28-358859ff9d9a.png)

Or I may be misunderstanding the instructions?:

> cache_from: Optional. An array of images to consider as cache, in order to reuse build steps from a previous build. The array elements are paths to directories generated by a get step with save: true.

here is my pipeline snippet:
```yaml
- name: image-test
  type: docker-image
  source:
    repository: my-repo/test

jobs:

- name: build-push-deploy

  plan:

  - aggregate:
    - get: git-test
      trigger: true
    - get: image-test
      params:
        save: true

  - put: image-test
    params:
      build: git-test
      dockerfile: git-test/Dockerfile
      tag: git-test/.git/ref
      tag_as_latest: true
      cache_from: [image-test]
    get_params:
      skip_download: true
```
