### ISSUE TITLE
Tags not applied correctly

### ISSUE THREAD

**Issue by javierholguera** [concourse/docker-image-resource#224]
I'm new to Concourse. I've started using this resource to upload to quay.io the result of a pipeline that builds a Docker image. This is my configuration:

```
resources:
- name: my-app-docker-image
  type: docker-image
  source:
    repository: quay.io:443/my-company/my-app
    username: my-user-in-quayio
    password: ((quay-io-password))

  - put: my-app-docker-image
    params:
      build: master/src/my-app
      build_args:
        NPM_TOKEN: ((npm-token))
      tag_file: master/VERSION
      additional_tag_names: [master/VERSION]
      tag_as_latest: true
```

What I've observed is the image will be uploaded to quay.io, but it will be tagged as "latest" only, ignoring the VERSION. I know the file does have a version on it because other parts of the pipeline use the same file and assign a version correctly.

Is this a known issue?

Thanks.
