### ISSUE TITLE
"tag_file" not working, but the depricated "tag" is still working 

### ISSUE THREAD

**Issue by saedalavinia** [concourse/docker-image-resource#228]
Not sure what I am missing here, but when I use tag_file it is not working, but the old tag (which the doc says it's now depricated) works just fine. 

Here is how I reproduce it on 3.14.1

```yaml
- name: setup
  plan:
  - get: git-repository
    trigger: true
  - task: create-tag-file
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source:
          repository: alpine
      outputs: 
      - name: tag
      run:
        path: /bin/sh
        args:
        - -c
        - |
            mkdir tag
            echo ((kops_version)) >> tag/tag
  - put: kops-image
    params:
      build: git-repository/docker/kops
      tag_file: tag/tag
      tag_as_latest: true
      build_args:
        KOPS_VERSION: ((kops_version))
```

This however works just fine: 

```yaml
- name: setup
  plan:
  - get: git-repository
    trigger: true
  - task: create-tag-file
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source:
          repository: alpine
      outputs: 
      - name: tag
      run:
        path: /bin/sh
        args:
        - -c
        - |
            mkdir tag
            echo ((kops_version)) >> tag/tag
  - put: kops-image
    params:
      build: git-repository/docker/kops
      tag: tag/tag
      tag_as_latest: true
      build_args:
        KOPS_VERSION: ((kops_version))
```

**Comment by vito** [comment]
Can you show what you mean by 'not working'? What error message do you see?

**Comment by testower** [comment]
I can't get either tag or tag_file to work. There is no error message, the tag is just never created or pushed. Only `latest` tag is created and pushed, regardless of whether the tag_as_latest option is provided.

**Comment by testower** [comment]
Resource:

```
- name: docker-image
  type: docker-image
  source:
    repository: ...
    aws_access_key_id: ...
    aws_secret_access_key: ...

- name: version
  type: semver
  source:
    initial_version: 1.0.0
    driver: git
    uri: ...
    branch: version
    file: version
    private_key: ...
```

Job:

- name: build-and-push
  serial_groups:
  - version
  plan:
  - get: repo
    trigger: true
  - get: version
    params:
      bump: minor
  - put: docker-image
    params:
      build: repo/((git_path_prefix))
      tag_file: version/version
      tag_prefix: v
      tag_as_latest: true
  - put: version
    params:
      file: version/version
  on_failure:
    put: slack-alert
    params: *slack-notification
```
