### ISSUE TITLE
Check fails on private registry

### ISSUE THREAD

**Issue by rubenv** [concourse/docker-image-resource#232]
I'm running a private registry using the standard docker distribution tools.

Get and put work fine, but for some reason all resources stay orange:

![screenshot from 2018-08-02 11-44-27](https://user-images.githubusercontent.com/42904/43576357-739cc150-9649-11e8-8a5b-f740c295e751.png)

This is caused by the check failing:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest: 401 Unauthorized
```

![screenshot from 2018-08-02 11-45-22](https://user-images.githubusercontent.com/42904/43576473-c35c5bf6-9649-11e8-9250-988c0ec1ba0b.png)

Note how there are revisions present (those are pushed). Pulls also work. It just seems that check fails to pass authentication info.

There's no magic in the resource configuration:

```
    - name: ergast-mirror-docker
      type: docker-image
      source:
          repository: registry.rocketeer.be/ergast-mirror
          username: ((docker-username))
          password: ((docker-password))
```

Is this a bug or am I overlooking something?
