### ISSUE TITLE
get_params: save: true fails

### ISSUE THREAD

**Issue by AndrewMorsillo** [concourse/docker-image-resource#237]
I have a put step where I use get_params: {save: true} but the next step in the job fails to find the image that was supposed to be saved.

Here is the relevant part of the pipeline. When I execute the job the put: app-image step fails with ```open app-image-stage1/image: no such file or directory```. It appears that app-image-stage1 isn't getting saved when it should.

resources:
```

  - name: node
    type: docker-image
    source:    
      repository: node
      tag: "8.12-alpine"

  - name: myapp-base
    type: docker-image
    source:    
      repository: gcr.io/myapp/myapp-base
      tag: "v0.0.3"
      username: _json_key
      password: ((service_account_json))
      
  - name: app-image-stage1
    type: docker-image
    source:
      repository: gcr.io/((project))/((image_name))
      tag: stage1-latest
      username: _json_key
      password: ((service_account_json))

  - name: app-image
    type: docker-image
    source:
      repository: gcr.io/((project))/((image_name))
      username: _json_key
      password: ((service_account_json))

  - name: app-source
    type: git
    source:
      uri: my_app_git_uri_goes_here
      branch: ((branch))
      tag_filter: ((tag_preamble))*

jobs:
  - name: build-image
    plan:
    - get: app-source
      trigger: true
    - task: get-version
      file: app-source/tasks/get-version.yaml
    - get: app-image
      params:
        save: true
    - get: node
      params:
        save: true
    - get: myapp-base
      params:
        save: true
    - get: app-image-stage1
      params:
        save: true
    # Execute stage1 of the build and push the image to the GCR repo
    - put: app-image-stage1
      params:
        build: app-source
        target_name: stage1
        load_bases:
          - node
          - myapp-base
        cache_from:
          - app-image-stage1
        get_params:
          save: true

    # Execute the final stage of the build with the cached stage1 part
    - put: app-image
      params:
        build: app-source
        load_bases:
          - node
        cache_from:
          - app-image
          - app-image-stage1
        tag: app-version/version
        get_params:
          skip_download: true
        tag_as_latest: true

```

**Comment by smoke** [comment]
I can confirm similar scenario in Concourse `v3.14.1` does not work for me too:
```
jobs:
  - name: accept-rc
    serial: true
    plan:
      - get: sv-platform-frontend-image-dev-cloud
        params:
          tag: dev-cloud-rc-latest
          save: true
        trigger: true
      - put: sv-platform-frontend-image
        params:
          load: sv-platform-frontend-image-dev-cloud
          tag: dev-cloud-rc-latest
          tag_as_latest: true
          get_params:
            save: true
      - aggregate:
          - put: sv-platform-frontend-image-dev-cloud
            params:
              load: sv-platform-frontend-image
              tag: prod-cloud-rc-latest
              get_params:
                skip_download: true
          - put: sv-platform-frontend-repo
            params:
              repository: sv-platform-frontend-repo
              force: true
              tag: prod-cloud-rc-latest
              only_tag: true
```
