### ISSUE TITLE
Make logging distinct

### ISSUE THREAD

**Issue by aequitas** [concourse/docker-image-resource#24]
This resource is often used as source for another resource when using resource types. When there is an error it is not always clear it is the `docker-image-resource` failing or an error message of the actual resource. 

Maybe a prefix could be added to the docker resource log/error output to make this distinction more clear?

**Comment by vito** [comment]
We plan to fix this in the UI properly but having a distinct output section for image fetching. Just gotta figure out the right UI first since technically there could be N levels deep of fetching (e.g. an `image_resource` that uses a custom resource type).

**Comment by xtremerui** [comment]
With the check mechanism nowadays I believe if there is an error coming from base resource type it will show properly.
With a pipeline 
```
resources:
- name: booklit
  type: hello-world-docker-image
  source: {uri: "https://github.com/vito/booklit"}

resource_types:
- name: hello-world-docker-image
  type: docker-image
  source:
    repository: concousre/blah-resource

jobs:
- name: unit
  serial: true
  plan:
  - get: booklit
    trigger: true
  - task: test
    file: booklit/ci/test.yml
```
fly check-resource result:

```
fly -t local cr -r test/booklit
id  name                      status   check_error
6   hello-world-docker-image  errored  run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest for image 'concousre/blah-resource:latest': 401 Unauthorized
does the image exist?
```
