### ISSUE TITLE
Inconsistent documentation / implementation

### ISSUE THREAD

**Issue by glennbech** [concourse/docker-image-resource#241]
If a resource is declared like this, the resource will (apparently) look for a file named RC and apply additional tags from that file. 
 
```    
- put: image
    params:
      additional_tags: RC
      build: dll
      skip_download: false
    get_params: {skip_download: true}
```

I suspect this behavior from the output I get 

```
waiting for docker to come up...
additional tags file 'RC' does not exist
```

However, the documentation says ```additional_tags: Optional. Path to a space separated list of tags. The Docker build will additionally be pushed with those tags.```
