### ISSUE TITLE
WARNING! Your password will be stored unencrypted in /root/.docker/config.json

### ISSUE THREAD

**Issue by chrishiestand** [concourse/docker-image-resource#243]
Using recent versions of the resource, e.g. 

```
resource_types:

- name: docker-image
  type: docker-image
  privileged: true
  source:
    repository: concourse/docker-image-resource
    tag: pr-208
```

Which contains docker version:
```
bash-4.4# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.11
 Git commit:        3b19bc6ba8
 Built:             Mon Sep  3 10:21:47 2018
 OS/Arch:           linux/amd64
 Experimental:      false
```

Using basic authentication we now get a docker warning in the build step:

> WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store

I suppose the actual security hasn't changed at all, but the warning will freak people out. This may be a compelling reason to abandon the local docker daemon approach sooner rather than later?
