### ISSUE TITLE
Support get "version" in docker-image-resource

### ISSUE THREAD

**Issue by petzah** [concourse/docker-image-resource#252]
Would it be possible to support "version" for get step for docker-image-resource. My scenario is:
1. have docker-image with multiple tags
2. build program for each tag

Something like this:

```yaml
---
resources:
- name: myrepo
  type: git
  source:
    uri: https://github/petzah/myrepo.git
    branch: concourse

- name: myimage
  type: docker-image
  source:
    repository: petzah/myimage

jobs:

- name: buildprogram_tag1
  plan:
  - get: myrepo
    trigger: true
  - get: myimage-tag1
    trigger: true
    resource: myimage
    version: {'tag': tag1}
  - task: build-tag1
    file: myrepo/ci/concourse/tasks/build.yml
    image: myimage-tag1

- name: buildprogram_tag2
  plan:
  - get: myrepo
    trigger: true
  - get: myimage-tag2
    trigger: true
    resource: myimage
    version: {'tag': tag2}
  - task: build-tag2
    file: myrepo/ci/concourse/tasks/build.yml
    image: myimage-tag2`
```
