### ISSUE TITLE
invalid reference format error in docker-image-resource put

### ISSUE THREAD

**Issue by chris-cinqsociety** [concourse/docker-image-resource#262]
Currently trying to build and push docker images, issue is that I'm receiving a this message from concourse during wordpress-release put step:

```
waiting for docker to come up...
invalid reference format
```
Here's the important bit of the Concourse Pipeline.
```
- name: wordpress-release
  type: docker-image
  source:
        repository: #############.dkr.ecr.eu-west-1.amazonaws.com/wordpress-release
        aws_access_key_id: #############
        aws_secret_access_key: #############
- name: mysql-release
  type: docker-image
  source:
        repository: #############.dkr.ecr.eu-west-1.amazonaws.com/mysql-release
        aws_access_key_id: #############
        aws_secret_access_key: #############
jobs:
- name: job-hello-world
  plan:
  - get: wordpress-website
  - task: write-release-tag
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: alpine/git }
      inputs:
        - name: wordpress-website
      outputs:
        - name: tags
      run:
        dir: wordpress-website
        path: sh
        args:
          - -exc
          - |
            printf $(basename $(git remote get-url origin) | sed 's/\.[^.]*$/-/')$(git tag --points-at HEAD) > ../tags/release-tag
  - put: wordpress-release
    params:
      build: ./wordpress-website/.
      dockerfile: wordpress-website/shared-wordpress-images/wordpress/wordpress-release/Dockerfile
      tag_file: tags/release-tag
  - put: mysql-release
    params:
      build: ./wordpress-website/
      dockerfile: wordpress-website/shared-wordpress-images/db/mysql-release/Dockerfile
      tag_file: tags/release-tag
```

Those images contain ```FROM #############.dkr.ecr.eu-west-1.amazonaws.com/shared-mysql``` (and shared-wordpress) could this be an issue?

The ```tag_file: tags/release-tag```, doesn't seem to be the issue as even without it, this still happens.

This is Concourse 5.0 running on top of Docker in Windows 10.

**Comment by GJKrupa** [comment]
We had this same issue.  Turned out that the Dockerfile had DOS line endings and it was treating the carriage return as part of the image tag.

**Comment by j-0ck3l** [comment]
Just had the same problem caused by including the tag in the resource name.

Correct format is:
```yaml
- name: docker-source-something
  type: docker-image
  source:
    repository: something/something-else
    tag: 'latest'
    username: user
    password: pass
```
