### ISSUE TITLE
get_params: save does not save image in v5.0.0

### ISSUE THREAD

**Issue by KleptoKat** [concourse/docker-image-resource#263]
I have a multi-stage docker build that I am trying to get caching to work with but when I put the docker resource with `get_params: {save: true}` it appears that the image is deleted from the folder and is not saved on the next build step.

I am running concourse v5.0.0.

Here is my setup:

```yaml

resources:

  - name: repo-release
    type: git
    source:
      uri: {{github-repo-uri}}
      branch: release
      private_key: {{github-private-key}}

  - name: frontend-image-base
    type: docker-image
    source: ((redacted))
  - name: frontend-image-builder
    type: docker-image
    source: ((redacted))
  - name: frontend-image
    type: docker-image
    source: ((redacted))

# JOBS
jobs:
  - name: build-frontend
    plan:
      - get: repo
        resource: repo-release
        trigger: true

      - get: frontend-image-builder
        inputs: # use blank inputs to decrease container file sizes
        params:
          save: true
      - get: frontend-image
        inputs:
        params:
          save: true
      - get: frontend-image-base
        inputs:
        params:
          save: true
        #/ End Aggregate


      # START BUILD (placed in do block for success/fail/cancel handles)
      - do:
        # BUILD BUILDER
        - put: frontend-image-builder
           get_params:
             skip_download: true
             save: true
           params:
             target_name: builder
             build: repo
             cache_from:
               - frontend-image-builder
             load_bases:
               - frontend-image-base

        # BUILDER RUNNER
        - put: frontend-image
           get_params:
             skip_download: true
           params:
             build: repo
             target_name: runner
             load_bases:
               - frontend-image-base
               - frontend-builder-new
             cache_from:
               - frontend-builder-new
               - frontend-image
             tag_as_latest: true
        on_success:
        on_failure:
        on_cancel:
```

When I run fly inspect on `put: frontend-image-builder` I can see the image in the frontend-image-builder folder.

When I run fly inspect on `put: frontend-image` I can only see digest, image-id, and tag in the frontend-image-builder folder. It looks like frontend-image-builder is deleting the image and it is not saving over for some reason. Is this a bug or am I doing something wrong here?

My workaround for the moment is to add a get in between the builder and the frontend which seems to be able to pull the latest frontend-image-builder. For example:

```yaml
...
# START BUILD
      - do:
        # BUILD BUILDER
        - put: frontend-image-builder
          # same as before
          
          # REGET BUILDER BECAUSE CONCOURSE HAS A BUG?
        - get: frontend-builder-new
          resource: frontend-image-builder
          inputs:
          params:
            save: true

        # BUILDER RUNNER
        - put: frontend-image
           # same as before
            load_bases:
              - frontend-image-base
              - frontend-builder-new # note different tag
            cache_from:
              - frontend-builder-new # note different tag
              - frontend-image
...
```

**Comment by vito** [comment]
You've got both `skip_download` and `save` configured. If `skip_download` is set there's nothing to download and thus nothing to save. Does it work if you remove `skip_download`?

**Comment by grabekm90** [comment]
I have a similar issue with concourse v5.8.0.
Please look at my simple example:
```
  - put: prod-image-1
    params:
      build: test-branch
      dockerfile: test-branch/((prod-image-1-dockerfile-path))
    get_params:
      # with skip_download the image is not saved for prod-image-2
      # skip_download: true
      save: true
  - put: prod-image-2
    params:
      load_base: prod-image-1
      build: test-branch
      dockerfile: test-branch/((prod-image-2-dockerfile-path))
    get_params:
      # now we can skip_download because the image is not used later
      skip_download: true
```

In this configuration, `prod-image-1` must be downloaded just after the build. We cannot add `skip_download: true` for the first image, because the image would not be saved.
It is weird because the image was just built :|
