### ISSUE TITLE
Support Secrets in Build

### ISSUE THREAD

**Issue by starpebble** [concourse/docker-image-resource#264]
_Issue_:
Support docker secret, in concourse jobs that build docker images.

_Reference_:

docker build has a --secret command line argument. It's different than --build-arg 
 https://docs.docker.com/engine/reference/commandline/build/

_Expected result_: 
A concourse job can pass a map of secrets to the a job.  Just like build-args.  

_Motivation_: 
Secrets will not show up in docker inspect.  build-args will show up in docker inspect.  secrets are safe for passwords.  build-args are not safe for passwords.

Concourse credential protected values must be valid values for a secret.  Then everything is safe.

docker build --secret is supported in: Docker API 1.39+

_Example_:
```
build_args:
  DO_THING: true
  HOW_MANY_THINGS: 2
  EMAIL: me@yopmail.com
  CI_BUILD_ID: concourse-$BUILD_ID
secrets:
  PASSWORD: {{secret_password}}
```
