### ISSUE TITLE
Adding git commit hashes as labels to docker image

### ISSUE THREAD

**Issue by koustubh25** [concourse/docker-image-resource#266]
I want to add a `version` and git commit `hash` as a label to the docker image. I understand I can use the `labels` tag like mentioned here https://github.com/concourse/docker-image-resource#out-push-an-image-or-build-and-push-a-dockerfile

However, my image label is dynamic. e.g. I want the following to add two labels `commit` and `hash`

```
- put: docker-registry
        params:
          additional_tags: myapp/.git/short_ref
          build: myapp
          tag_as_latest: true
          tag_file: version/number
          labels: 
            commit: myapp/.git/short_ref
            version: version
```

However, the commit hash and the version values are considered as string and when I do `docker inspect`, I can just find the values of these to be `myapp/.git/short_ref` and `version`.

Is there any way I can print the contents of this file and assign them to `commit` and `version`?

The relevant code seems to be here
https://github.com/concourse/docker-image-resource/blob/master/assets/out#L68
