### ISSUE TITLE
assets/in script does not handle images built using "scratch" repo

### ISSUE THREAD

**Issue by robdaemon** [concourse/docker-image-resource#27]
Given this pipeline configuration, builds always fail because the source image uses `scratch` as a `FROM`, so there is no `/etc/passwd` file.

Pipeline configuration:

```yaml
jobs:
  - name: docker-images
    plan:
      - get: nats-image-in
      - put: nats-image-out

resources:
  - name: nats-image-in
    type: docker-image
    source:
      repository: nats
      tag: 0.7.2

  - name: nats-image-out
    type: docker-image
    source:
      insecure_registries: ["192.168.41.159:5000"]
      repository: 192.168.41.159:5000/my-repo/nats
      tag: mytag
```

Bug is around here: https://github.com/concourse/docker-image-resource/blob/747c43afda713b0447f3327cd312985f568f6d8d/assets/in#L62-L66

`print-metadata` should handle this scenario gracefully, these are perfectly valid Docker images.
