### ISSUE TITLE
Can't connect to Docker daemon when using hijack on resource container

### ISSUE THREAD

**Issue by trevorhodges** [concourse/docker-image-resource#274]
I'm trying to troubleshoot an Artifactory permissions issue with the pipeline shown below. Strangely, when I attempt the put to `artifactory` I get the error:

`unauthorized: The client does not have permission to push to the repository.`

This is despite being able to push the image to Artifactory using the same user/pass and docker cli on my laptop.

To troubleshoot this further I hijack the container for the put step and try to import the image's tarball. This results in the following error:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Now this is a little surprising to me. I'd think that the resource's container would be running with privilege and able to connect to the daemon? Is something different about this when using `hijack` vs. the normal job step running?

Any ideas for how to further troubleshoot this?

Thanks in advance.

```
resources:
- name: image-repo
  type: git
  source:
    branch: master
    private_key: ((private_key))
    uri: ssh://git@git-server/repo.git

- name: artifactory
  type: docker-image
  source:
    repository: artifactory.server.com:2077/((repo))
    tag: latest
    username: ((destination_username))
    password: ((destination_password))

jobs:
- name: update-image
  plan:
  - get: image-repo
  - task: do-stuff
    file: image-repo/scripts/do-stuff.yml
    vars:
      repository-directory: ((repo))
  - task: build-image
    privileged: true
    file: image-repo/scripts/build-image.yml
  - put: artifactory
    params:
      import_file: image/image.tar
```
