### ISSUE TITLE
Error during connect EOF

### ISSUE THREAD

**Issue by jinxac** [concourse/docker-image-resource#288]
I was trying to integrate this with ECR and following is my YAML file:-

```
 ---
resources:
  - name: phoenix-resource
    type: git
    source:
      uri: ((private_repo))
      branch: develop
      private_key: ((private-repo-key))

  - name: ecr-docker-reg
    type: docker-image
    source:
      aws_access_key_id: ((private_aws_id))
      aws_secret_access_key: ((private_aws_key))
      repository: ((private_aws_repo))

  - name: ssh-key
    type: s3
    source:
      bucket: dev-deployments-concourse
      versioned_file: bitbuck
      access_key_id: ((private_aws_id))
      secret_access_key:((private_aws_key))

jobs:
  - name: phoenix-dev
    public: true
    plan:
      - get: phoenix-resource
      - get: ssh-key
      - put: ecr-docker-reg
        params:
          build: phoenix-resource

```

In this I am getting error as follows:-

```
waiting for docker to come up...
Sending build context to Docker daemon  9.779MB
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=concourse%2Fgit-resource%3Alatest&target=&ulimits=null&version=1: EOF

```

Can someone please help me on this? TIA

**Comment by jinxac** [comment]
Hi,

I found the issue, I was not getting the ecr-docker-reg. Following works:-


```
 ---
resources:
  - name: phoenix-resource
    type: git
    source:
      uri: ((private_repo))
      branch: develop
      private_key: ((private-repo-key))

  - name: ecr-docker-reg
    type: docker-image
    source:
      aws_access_key_id: ((private_aws_id))
      aws_secret_access_key: ((private_aws_key))
      repository: ((private_aws_repo))

  - name: ssh-key
    type: s3
    source:
      bucket: dev-deployments-concourse
      versioned_file: bitbuck
      access_key_id: ((private_aws_id))
      secret_access_key:((private_aws_key))

jobs:
  - name: phoenix-dev
    public: true
    plan:
      - get: phoenix-resource
      - get: ssh-key
      - get: ecr-docker-reg . //Adding this line
      - put: ecr-docker-reg
        params:
          build: phoenix-resource
```
