### ISSUE TITLE
Unable to specify 'load_tag' dynamically from the pipeline task

### ISSUE THREAD

**Issue by holgerstolzenberg** [concourse/docker-image-resource#296]
Currently it is not possible to gather the `load_tag` dynamically during the pipeline execution by for example reading it from a previously generated file (like done with `tag_file`).

**Comment by vito** [comment]
This should be done by using the [`load_var` step](https://concourse-ci.org/jobs.html#load-var-step):

```yaml
plan:
- # ...
- load_var: foo
  file: path/to/tag
- put: resource
  params: {load_tag: ((.:foo))}
```

The idea behind the `load_var` step is to allow resource type implementations to simplify and focus on static values, rather than having to implement `foo` and `foo_file` forms of every param.

This step was newly added in v6.0 - it's currently marked experimental, but its RFC has since been merged, so I think we can un-flag it. 👍
