### ISSUE TITLE
How to pull and push a specific tagged docker image?

### ISSUE THREAD

**Issue by nischit7** [concourse/docker-image-resource#299]
I am trying to use this Concourse CI resource to pulling specific "tagged" docker image. 
I tried working out a solution using both https://github.com/concourse/registry-image-resource and https://github.com/concourse/docker-image-resource.
From the documentation, I dont see a way to achieve it.

In the below approach, Its declared as a resource and the tag remains same for rest of the execution.
```
  - name: server-docker-image-artifactory
    type: docker-image
    icon: docker
    source:
      username: username
      password: password
      tag: "mytag"
      repository: repo

  - name: server-docker-image-bintray
    type: docker-image
    icon: docker
    source:
      username: username
      password: password
      tag: "mytag"
      repository: repo
```

What I would like to achieve is, when declaring multiple steps, I would like to do something as below.

```
plan:
    # Pull an image with a "tag" that was derived by some step in the pipeline
    - get: server-docker-image-artifactory
       params:
           tag: my-dynamic tag

    # Copy that specific tagged image from artifactory to bintray
    - put: server-docker-image-bintray
       inputs: ["server-docker-image-artifactory", "my-dynamic tag"]
       params:
           load: server-docker-image-artifactory
           tag_file: my-dynamic tag

````

Right now... i am unable to provide something like above. It always ends up pulling the latest image.
I tried the params such as "load", "load_file", "load_tag". But no luck
Any directions?

**Comment by dragonchaser** [comment]
I am having the same issue here with a similar configuration
```
        - put: docker.myregistry
          params:
            load_repository: "myregistry/myimage"
            load_file: OUTPUTS/image.tar # pulled in from a previous step
            tag_file: OUTPUTS/my-dynamic.tag.txt # also pulled in from a previous step
```
Concourse always tries to push "myregistry/myimage:latest" even though the tag is specified in the tag_file.
All other experiments failed aswell (providing `tag` etc.)
