### ISSUE TITLE
Docker Image will be tagged as latest when tag_file is empty regardless of tag_as_latest: false

### ISSUE THREAD

**Issue by dangkh0** [concourse/docker-image-resource#304]
cc: @avanier

Hi

I would like to clarify that if `tag_file` is empty and `tag_as_latest` is set to false, Concourse will still build a Docker image with the tag **latest**. The solution is to provide a `tag_file` param.

Initially my intention was to build a Docker image with tags only listed in `additional_tags` and **skip the latest tag** using the `tag_as_latest: false` as a param. See below:
```
- put: docker-image
        get_params: {skip_download: true}
        inputs:
          - git-repo
          - docker_build_context_folder
  params:
        build: git-repo
        build_args_file: docker_build_context_folder/args.json
        additional_tags: docker_build_context_folder/tags_list
        tag_as_latest: false
```

But this set-up will generate an image using the latest tag and tags listed in `additional_tags`

**Solution:**
I removed one of the tags from `additional_tags` list and used it for `tag_file`.

```
- put: docker-image
        get_params: {skip_download: true}
        inputs:
          - git-repo
          - docker_build_context_folder
  params:
        build: git-repo
        build_args_file: docker_build_context_folder/args.json
        tag_file: docker_build_context_folder/tag
        additional_tags: docker_build_context_folder/tags_list
```

**Request:**
I don't think this issue requires a code change but perhaps better clarify the relationship between `tag_file` and `tag_as_latest`  in the README.md documentation

Thank You
