### ISSUE TITLE
PR 300 causes issues with "redhat" repository

### ISSUE THREAD

**Issue by andrew-edgar** [concourse/docker-image-resource#307]
The recent PR 300 which uses HEAD to check the resources causes the following errors when access "redhat" image repository.

"run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1

stderr:
no digest header returned"

We have the resource configured like this ...

```
  - name: base-image-logdna-agent
    source:
      repository: registry.access.redhat.com/ubi8/nodejs-12
      tag: latest
    type: docker-image
```

We had to revert to using 1.3.4 of the docker-image-resource for all "redhat" repositories.  We need this PR to be rolled back or fixed so that this is not the "default" and that we can perhaps have a source property to define that we do NOT use HEAD when doing the check for certain repositories.
