### ISSUE TITLE
Cannot change default Docker STARTUP_TIMEOUT

### ISSUE THREAD

**Issue by holgerstolzenberg** [concourse/docker-image-resource#309]
We are running into 

<img width="568" alt="Screenshot 2020-10-20 at 10 29 49" src="https://user-images.githubusercontent.com/282736/96560913-31e3d380-12bf-11eb-8560-dcda21d80787.png">

very often.

I tried to overcome this by adding a `STARTUP_TIMEOUT` to the put steps params, but it seems to have no effect.

```yaml
- put: artifactory-docker-image
  params:
    load_tag: ((.:version-from-file))
    load_file: master-branch/build/image.tar
    load_repository: ((artifact_image_path))/((artifact_id))
    tag_file: version/version
    tag_as_latest: true
    STARTUP_TIMEOUT: 180
  get_params:
    skip_download: true
```

If the setting being ignored is not a bug, how can this timeout be configured?
