### ISSUE TITLE
PUT doesn't add ref to INPUT when registry mirror is set.

### ISSUE THREAD

**Issue by Typositoire** [concourse/docker-image-resource#313]
**Disclaimer, this could be just because of a specific registry mirror, we use Artifactory.**

Context: So with the Docker Hub rate limit hell, we upgraded to Concourse 6.7.0 and setup a registry-mirror for `docker-image` and `registry-image`.

Issue: We have a build step that is then used by a task right after.

```
- name: build-pull-request
  plan:
  - get: pull-request
  - get: labels
  - put: ci-image
    inputs:
    - pull-request
    - labels
    get_params: { skip_download: true }
    params:
      cache: true
      build: pull-request
      tag_file: ./labels/tag_ci
      labels_file: ./labels/file.json
      target_name: dev
      build_args:
        ARTIFACTORY_CREDENTIALS: ((artifactory.username)):((artifactory.password))
- name: do-stuff
  plan:
    - get: ci-image
      passed: [build-pull-request]
      version: every
      trigger: true
```

And what happens is that when the `put: ci-image` is done, `get: ci-image` in `do-stuff` never gets its input.

We did the following and it fixed it.

```
- name: docker-image-no-mirror
  type: registry-image
  privileged: true
  source:
    repository: concourse/docker-image-resource
    tag: 1.5.1
```

And changed the type of ci-image to `docker-image-no-mirror` and VOILA, refs are filled correctly now.

**Comment by Typositoire** [comment]
I've been trying to reproduce that for the last 2 hours without luck... I can confirm by the audit logs that the PUT generate a good digest. I tried locally with the image `1.5.1` and I always get the latest and cursor digest. I have no idea why using the bundled docker-image in v6.7.X I have a different behavior ...

**Comment by mischcon** [comment]
I can confirm that using Concourse v6.7.0 with the built-in version of docker-image-resource (1.5.0) that dependend downstream jobs do not get triggered if a artifact gets produced / pushed by the docker-image-resource.

The workaround described above works for me.
I added the "registry-mirror" manually to the resource - still everything works fine.

```
resources:
- name: ci-image
  type: docker-image-no-mirror
  icon: docker
  source:
    registry_mirror: https://link.to.custom.mirror
    repository: ....
    tag: ...
```
