### ISSUE TITLE
build image error

### ISSUE THREAD

**Issue by yeyuexia** [concourse/docker-image-resource#32]
hi,
  i found when i build image and the FROM IMAGE in Dockerfile is a private registry image and the registry address different with the pushed registry,  concourse would tell me no basic auth credentials.
Furthermore,  when i try get the FROM IMAGE before build in task,  when running docker build, the FROM IMAGE still need to be download from registry.

below are the sample config.

pipeline.yml:

```
resources:
    - name: image need be build and push
      type: docker-image
      source:
        repository: registry1
    - name: the FROM IMAGE
      type: docker-image
      source:
        repository: registry2

jobs:
    - name: build image and push
      plan:
        - get: the FROM IMAGE
        - put: image need be build and push
          params:
            dockerfile: Dockerfile
```

Dockerfile:

```
FROM registry2
...
```
