### ISSUE TITLE
support public.ecr.aws

### ISSUE THREAD

**Issue by gdamjan** [concourse/docker-image-resource#322]
AWS has introduced public ECR registries, and when configured the url of the registry is `public.ecr.aws`. The same url is used for both push and pull.

docker-image-resource currently won't supply AWS credentials unless it matches the ECR regex
https://github.com/concourse/docker-image-resource/blob/master/assets/out#L232

https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/

**Comment by vidolch** [comment]
Is there any development in this? Seems like pushing public image is not working:
```
WARN[0000] ECR integration is experimental and untested 
INFO[0002] pushing tag(s) latest
ERRO[0002] pushing image failed: pushing tag(s): POST https://********.dkr.ecr.*******.amazonaws.com/v2/********/blobs/uploads/: NAME_UNKNOWN: The repository with name '********' does not exist in the registry with id '********' 
```

**Comment by eckdanny** [comment]
The \[simplest/most-common?\] use-case for public ECR instead of Docker Hub (subject to [rate-limits](https://docs.docker.com/docker-hub/download-rate-limit/#:~:text=Docker%20Hub%20limits%20the%20number,pulls%20per%206%20hour%20period.)):

> _...workloads running in AWS will get unlimited data bandwidth from any region when pulling publicly shared images hosted on AWS._<br />[-AWS](https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/)

If @gdamjan's sleuthing is correct, that RegEx constraint should _definitely_ be relaxed in order for a simple pipeline (below) to work, rt? https://github.com/concourse/docker-image-resource/blob/273da71dd43b27748908897e516f016c52266fe1/assets/out#L232

<details><summary>simple pipeline</summary>

```yaml
---
resources:
- name: node-image
  type: registry-image
  source:
    tag: lts-gallium
    repository: public.ecr.aws/docker/library/node
[...]

jobs:
- name: my-job
  plan:
    - task: use-node-image
      image: node-image
      config: [...]
```

</details>
