### ISSUE TITLE
[HELP] custom path for dockerfile 

### ISSUE THREAD

**Issue by stiliajohny** [concourse/docker-image-resource#341]
hi 
This is an issue seeking help

Reading the document on the section [out](https://github.com/concourse/docker-image-resource#out-push-an-image-or-build-and-push-a-dockerfile) I couldn't quite figure- out how to specify a dockerfile 

Here is yaml if anyone could give me some help 
Thanks in advance 

```yaml
jobs:
- name: build-and-push-image
  plan:
  - get: example-image-source
    tags:
    - worker-dev
  - task: build-task-image
    tags:
      - worker-dev
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: example-image-source
      outputs:
      - name: image
      params:
        CONTEXT: example-image-source
        dockerfile: ./example-image-source/Dockerfile.custom
      run:
        path: build
  - put: example-image
    params:
      image: image/image.tar
      dockerfile: ./example-image/Dockerfile.custom
```

**Comment by stiliajohny** [comment]
answering my own question 
The resource documentation is not the correct one to read for this sort of mod 

Read here https://github.com/concourse/oci-build-task 

The yaml now looks like 

```yaml
jobs:
- name: build-and-push-image
  plan:
  - get: example-image-source
    tags:
    - worker-dev
  - task: build-task-image
    tags:
      - worker-dev
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: example-image-source
      outputs:
      - name: image
      params:
        CONTEXT: example-image-source
        DOCKERFILE: ./example-image-source/Dockerfile.custom  ;<<------ here 
      run:
        path: build
  - put: example-image
    params:
      image: image/image.tar
      dockerfile: ./example-image/Dockerfile.custom
```
