### ISSUE TITLE
Unable to push/pull images from ECR on AWS GovCloud

### ISSUE THREAD

**Issue by bartlettt** [concourse/docker-image-resource#346]
This resource is incompatible with ECR on AWS GovCloud. This is because the version of Amazon ECR Credentials Helper is very out of date. 

# Reproduction

```
resources:
  - name: my-image
    type: docker-image
    source:
      repository: 000000000000.dkr.ecr.us-gov-west-1.amazonaws.com/my-image
      aws_access_key_id: XXXXXXXXXXX
      aws_secret_access_key: YYYYYYYYYYY
  - name: repo
    type: git
    source:
      uri: example.git
jobs:
    - get: repo
    - put: my-image
      params:
        build: repo
        dockerfile: Dockerfile
      get_params:
        save: true
```

# Resolution
I attempted to update `go.mod` to use the following:
```
require (
  ...
  github.com/awslabs/amazon-ecr-credential-helper v0.6.0
  ...
)
```

But I'm not much of a Go programmer, so couldn't get the container to build properly.

# Workaround
As a workaround I added the updated binary after the container was built which solved the problem.

```Dockerfile
FROM concourse/docker-image-resource:1.6.3
ADD --chown=root:root https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.6.0/linux-amd64/docker-credential-ecr-login /opt/resource/ecr-login
RUN chmod +x /opt/resource/ecr-login
```
