### ISSUE TITLE
Docker image tag `get` stage override

### ISSUE THREAD

**Issue by sfuerte** [concourse/docker-image-resource#350]
Is it possible to add support for the subject feature? 

Right now an image's tag can be supplied for the source only, i.e. once for the whole pipeline:

```yaml
  - name: my_image
    type: docker-image
    icon: docker
    source:
      repository: <some registry>
      tag: X.Y.Z
      <<: *repository_credentials
```

The idea (and necessity) to have it overridden per task, e.g. per environment used (dev / stage / prod):
```yaml

  - name: build-dev
    plan:
      - get: my_image
        params:
          save: true
          tag: "X.Y.Z+1"  # tag override here
```

as a bonus, with such override it can be dynamic via `load_vars` step from a shared config source.
