### ISSUE TITLE
Amazon ECR Support Proposal

### ISSUE THREAD

**Issue by eploko** [concourse/docker-image-resource#36]
### The Scope of the Problem

I've been playing with Concourse for some time. As it turns out there's just a single thing that keeps me from bringing it into our CI process: I couldn't find a way to provide ECR credentials to the docker-image resource.

The problem lies in the fact that the ECR uses temporary tokens to provide access to repos. One would naïvely try to obtain the token manually and provide it to the resource as the password. But then the token expires in 12 hours and the pipeline fails to push the image. In this state the whole idea of Concourse as a CI system is kind of pointless, as one needs to update the credentials in the pipeline.yml file and then push the pipeline via fly each 12 hours.

### How This Could Be Improved Upon

When the `repository` param for the resource is set to an ECR repo like `XXXX.dkr.ecr.REGION.amazonaws.com/REPO_NAME`, the resource may treat the `username` and `password` fields as the AWS access and secret keys. It would then use these to fetch an ECR token from AWS and use that for further docker calls.

Do you think this would be an adequate strategy for tackling the problem?

I would be happy to try to implement this and make a PR if this all makes sense.

**Comment by smazurov** [comment]
I'm evaluating Concourse now, and because we heavily use ECR, this is also an issue for us. Any chance the PR gets merged?

**Comment by farahfa** [comment]
I got tired of waiting so, I've created a resource based on eploko's fix and it works just fine!

Here's my pipeline that includes this resource for reference.

```
resource_types:
- name: aws-ecr-docker-registry
  type: docker-image
  source:
    repository: covisintrnd/ecr-docker-image-resource

resources:
- name: nexus-docker-image
  type: aws-ecr-docker-registry
  source:
    username: {{aws_access_key_id}}
    password: {{aws_secret_access_key}}
    aws_region: {{ecr_region}}
    repository: {{ecr-nexus-repo}}
    tag: test
```

I'm running into a small issue where if push an image to ECR it pulls it after, not sure if it's something related to this or not, but it's something to be aware of.
