### ISSUE TITLE
Docker Cache 

### ISSUE THREAD

**Issue by ppiccolo** [concourse/docker-image-resource#45]
Hello,

can you please add some other example ... in particular how to use the docker caching layer to (re)build the image.

actually my pipeline is this :
```yml
resources:
- name: python2.7_source
  type: git
  source:
    uri: http://concourseci:concourseci@gitlab.my_domain.lan/group_xxx/python.2.7.git
    branch: master
    paths: [Dockerfile]

- name: python2.7_image
  type: docker-image
  source:
    insecure_registries:
      - registry.my_domain.lan:5000
    repository: registry.my_domain.lan:5000/my.python2.7

jobs:
- name: python2.7_build
  plan:
    - get: python2.7_source
      trigger: true
    - put: python2.7_image
      params: {build: python2.7_source, cache: true }
```
but as doc say if the image still don't exist job fail .... how to overcome this ?

Tnx in advance

**Comment by ppiccolo** [comment]
One step forward 

```yml

resources:
- name: python2.7_source
  type: git
  source:
    uri: http://concourseci:concourseci@gitlab.my_domain.lan/my_domain-group/python.2.7.git
    branch: master
    check_every: 3s

- name: python2.7_image
  type: docker-image
  source:
    insecure_registries:
      - registry.my_domain.lan:5000
    repository: registry.my_domain.lan:5000/my_domain.python2.7


jobs:
- name: python2.7_build
  plan:
  - get: python2.7_source
    trigger: true
  - put: python2.7_image
    params: {build: python2.7_source, cache: true}
    on_failure:
      put: python2.7_image
      params: {build: python2.7_source, cache: false}
```

ok simply adding on_failure handler to execute the "First build", the problem is :

> Sending build context to Docker daemon  24.6 MB
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
6599cadaf950: Already exists
23eda618d451: Already exists
f0be3084efe9: Already exists
52de432f084b: Already exists
a3ed95caeb02: Already exists
Digest: sha256:15b79a6654811c8d992ebacdfbd5152fcf3d165e374e264076aa435214a947a3
Status: Downloaded newer image for ubuntu:14.04
 ---> 90d5884b1ee0
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in bffeb0aabbf0
 ---> 7dc59b56f42b
Removing intermediate container bffeb0aabbf0
Step 3 : RUN echo "Hello"
 ---> Running in 602a000b8a57
Hello
 ---> 309a2d0aece2
Removing intermediate container 602a000b8a57
Step 4 : RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in af22934ac1f8
 ---> ec59abef11e7
Removing intermediate container af22934ac1f8
Successfully built ec59abef11e7

as you can see the docker build process don't take into account layers already created.

What I'm missing... ? 

Thanks in advance
