### ISSUE TITLE
Not able to use custom build base image with private registry

### ISSUE THREAD

**Issue by baszalmstra** [concourse/docker-image-resource#47]
I'm building several docker images that use a common base image. I push all these images to a private registry on my local network. Building the base image and pushing it to the registry works like a charm but when building the derived imaged (cross-compiler-darwin-x64) I'm unable to fetch the base image. It always tries to pull the base image from docker.io regardless of me docker loading the base image upfront.

Is there an error in my configuration?

This is my configuration:

```
resource:
- name: cross-compiler-base
  type: docker-image
  source:
    repository: 192.168.1.128:5000/baszalmstra/cross-compiler-base
    insecure_registries: [
      "192.168.1.128:5000"
    ]

- name: cross-compiler-darwin-x64
  type: docker-image
  source:
    repository: 192.168.1.128:5000/baszalmstra/cross-compiler-darwin-x64
    insecure_registries: [
      "192.168.1.128:5000"
    ]

jobs:
- name: build-base
  plan:
  - get: cross-compiler-source
    trigger: true
  - put: cross-compiler-base
    params: { build: cross-compiler-source }

- name: build-darwin-x64
  plan:
  - aggregate:
    - get: cross-compiler-source
      trigger: true
      passed: [build-base]
    - get: cross-compiler-base
      passed: [build-base]
      trigger: true
      params: {save: true}
  - put: cross-compiler-darwin-x64
    params:
      build: cross-compiler-source/darwin-x64
      load_base: cross-compiler-base
    get_params: {rootfs: true}
```

This is the error I get:

```
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM baszalmstra/cross-compiler-base
Pulling repository docker.io/baszalmstra/cross-compiler-base
Error: image baszalmstra/cross-compiler-base not found
```
