### ISSUE TITLE
Not a valid repository/tag @for

### ISSUE THREAD

**Issue by Gisleburt** [concourse/docker-image-resource#48]
Get the following error when trying to "put" a docker image into an insecure registry (note: I haven't tried this with a proper repo).

```
Pulling my.insecure.registry:5000/my/application@for (attempt 3 of 3)...
Error parsing reference: "my.insecure.registry:5000/my/application@for" is not a valid repository/tag
```
```
Pulling my.insecure.registry:5000/my/styleguide@for (attempt 3 of 3)...
Error parsing reference: "my.insecure.registry:5000/my/styleguide@for" is not a valid repository/tag
```
Here are the resources:
```yaml
  - name: application-service
    type: docker-image
    source:
      repository: "my.insecure.registry:5000/my/application"
      insecure_registries: [ "my.insecure.registry:5000" ]

  - name: styleguide-service
    type: docker-image
    source:
      repository: "my.insecure.registry:5000/my/styleguide"
      insecure_registries: [ "my.insecure.registry:5000" ]
```
