### ISSUE TITLE
Support .dockerignore via params

### ISSUE THREAD

**Issue by vito** [concourse/docker-image-resource#60]
Would be nice for occasions like this:

``` yaml
- name: build-atc-ci
  public: true
  serial: true
  plan:
  - aggregate:
    - get: concourse-atc-ci
      trigger: true
    - get: selenium-firefox
      trigger: true
      params: {save: true}
    - get: golang-1.7
      trigger: true
  - put: concourse-atc-ci-image
    params:
      load_base: selenium-firefox
      build: .
      dockerfile: concourse-atc-ci/Dockerfile # needs golang-*
      ignore: [selenium-firefox]
```
