### ISSUE TITLE
Support for Google Container Registry?

### ISSUE THREAD

**Issue by josdotso** [concourse/docker-image-resource#73]
Usually, I can use `gcloud docker -a` before running docker commands that don't understand GCR and get by, but that doesn't seem to be working for me with `concourse/lite` Vagrant box.

https://cloud.google.com/container-registry/docs/advanced-authentication

Is GCR supported?

**Comment by vito** [comment]
I suppose this'll need changes similar to supporting Amazon ECR. Don't know enough about Google's registry, myself.

**Comment by MaikuMori** [comment]
It already works if you follow the tutorial which you linked:

```
 - name: build-image
   type: docker-image
   source:
     repository: gcr.io/project/repo
     username: _json_key
     password: {{gcr-key}}
```

You need to use `username` set to `_json_key`. And password is the `json` key file for your service account.
