### ISSUE TITLE
Using resource in "get" doesn't populate /tag correctly

### ISSUE THREAD

**Issue by fatih** [concourse/docker-image-resource#78]
Hi,

First I have a file called `image_tag` with the following content:

```sh
123abc
```

I'm using the resource in get  and then as put in another job, a simplified example.:

```
jobs:
  - name: build
    plan:
      - task: build
        file: build.yml
      - put: my-image
        params:
          build: build
          tag: build/image_tag
  - name: deploy
    plan:
      - get: my-image
        passed: [build]
        trigger: true    
        params:
          skip-download: true
      - task: deploy
        file: deploy.yml
```

So according to the README, it says:

```
/tag: The tag of the repository that was fetched.
```

However when I fetch it I see this:

```
root@f688e206-4802-4915-4082-7ad25f7dfa2e:/tmp/build/b0d51b9f/my-image# cat tag
latest
```

But if you look at my jobs, and especially at the `put` params, you see I don't use `latest`. Instead I'm using my own tag file with the content `123abc`. 

I assume that with `get`, the content of `/tag` should also be `123abc`, but right now it's not. 

Do I miss something or is `/tag` always latest?
