### ISSUE TITLE
Image cannot be pull after build

### ISSUE THREAD

**Issue by vtajzich** [concourse/docker-image-resource#91]
I Have configuration like:

```
- resources:
   - name: my-docker-resource
     type: docker-image
     source:
       repository: registry.org.com:5000/a-image
       tag: concourse-latest        

jobs:

....

- put: my-docker-resource
    params:
      build: directory
```

Job is built, image pushed. Pull fails w/ message:

```
Failed to pull image registry.org.com:5000/a-image@for.
```

Why is there tag "@for" ? Where it comes from?
