### ISSUE TITLE
skip_download does download the image

### ISSUE THREAD

**Issue by stingA0815** [concourse/docker-image-resource#94]
Hey Folks,

I recogniced high pull rates on my images since I set an pipeline to the image. https://github.com/concourse/docker-image-resource/blob/master/assets/in#L62 might it be possible that skip_download will produce an "official docker hub pull"?
```
      - get: "docker-mydockerimage"
        trigger: true
        get_params:
          skip_download: true
```

**Comment by stingA0815** [comment]
the pipeline configuration is available at https://github.com/stingA0815/docker-archlinux-abs

**Comment by chendrix** [comment]
Hi there, sorry your issue has gone unsupported until now. You may have figured this out by now but you should be using `params` instead of `get_params`!

```
      - get: "docker-mydockerimage"
        trigger: true
        params:
          skip_download: true
```
