### ISSUE TITLE
rootfs dir is always created

### ISSUE THREAD

**Issue by ashb** [concourse/docker-image-resource#95]
Looking at the code and running `fly intercept` I see that `docker export` is always run creating `rootfs/` in the build dir.

My pipeline is this:

```
---
resources:
- name: project-repo
  type: git
  source:
    uri: git@github.com:org/project
    branch: concourse-pipeline
    private_key: {{github_private_key}}
- name: centos-baseimage
  type: docker-image
  source:
    repository: centos
    tag: "6"
- name: baseimage
  type: docker-image
  source:
    repository: private-repo.com:443/project/common

jobs:
- name: common-build
  plan:
  - get: project-repo
  - get: centos-baseimage
  - put: baseimage
    params:
      build: project-repo/11.1/common
```

And then in the garden executor I see this:

```
bash-4.3# ls -altr /tmp/build/put/centos-baseimage/rootfs/
total 0
drwxr-xr-x    1 root     root             0 Sep 23  2011 srv
drwxr-xr-x    1 root     root             0 Sep 23  2011 opt
drwxr-xr-x    1 root     root             0 Sep 23  2011 mnt
drwxr-xr-x    1 root     root             0 Sep 23  2011 media
drwxr-xr-x    1 root     root             0 Sep 23  2011 home
drwx------    1 root     root             0 Nov  2 12:51 lost+found
drwxr-xr-x    1 root     root             0 Nov  2 12:51 selinux
drwxr-xr-x    1 root     root           126 Nov  2 12:51 var
drwxr-xr-x    1 root     root           106 Nov  2 12:51 usr
dr-xr-x---    1 root     root           178 Nov  2 12:53 root
dr-xr-xr-x    1 root     root           798 Nov  2 12:53 sbin
dr-xr-xr-x    1 root     root          4644 Nov  2 12:53 lib64
dr-xr-xr-x    1 root     root            70 Nov  2 12:53 lib
dr-xr-xr-x    1 root     root           578 Nov  2 12:53 bin
drwxr-xr-x    1 root     root             0 Feb  7 14:57 sys
drwxr-xr-x    1 root     root             0 Feb  7 14:57 proc
drwxr-xr-x    1 root     root          1690 Feb  7 14:57 etc
drwxr-xr-x    1 root     root             0 Feb  7 14:57 dev
-rwxr-xr-x    1 root     root             0 Feb  7 14:57 .dockerenv
drwxrwxrwt    1 root     root            76 Feb  7 14:57 tmp
drwxr-xr-x    1 root     root           130 Feb  7 14:57 ..
drwxr-xr-x    1 root     root           172 Feb  7 14:57 .
bash-4.3# du -sch /tmp/build/put/centos-baseimage/rootfs/
201.5M  /tmp/build/put/centos-baseimage/rootfs/
201.5M  total
```

What is the point of this? Is it always required, or can it be disabled? A 200MiB dir isn't a huge problem, but I'm trying to build some "Enterprise" software and the images are 5-10GiB and I don't want or need that copied around. (or even just to use up that much disk space when the job is running).

**Comment by andrewedstrom** [comment]
@ashb are you still experiencing this issue in 3.1.x?

**Comment by ashb** [comment]
I'm not currently using concourse so can't check, but the code hasn't changed: https://github.com/concourse/docker-image-resource/blob/7ffaffb69b052c02cffa9a1bfed30b355af2c453/assets/in#L79-L84

```sh
  mkdir -p ${destination}/rootfs/
  docker export $(cat /tmp/container.cid) | tar --exclude="dev/*" -xf - -C ${destination}/rootfs/

  if [ "$rootfs" = "true" ]; then
    docker export $(cat /tmp/container.cid) > ${destination}/rootfs.tar
fi
```

If you ask for rootfs you get a rootfs.tar, but you always get the rootfs/ folder too.

**Comment by chendrix** [comment]
The `/rootfs` dir contains the actual contents of the image. This is *required* behavior of the docker-image-resource.

When you use a volume as an `image` in Concourse, it's actually the contents of the `/rootfs` dir in the volume that get loaded as the image for whatever container that gets spun up.

If in your particular pipeline you're interested in making this more performant, you can always make it 

```
...
  - put: baseimage
    params:
      build: project-repo/11.1/common
      get_params: {skip_download: true}
```
