### ISSUE TITLE
get with trigger is only working once

### ISSUE THREAD

**Issue by nexeck** [concourse/docker-image-resource#96]
Jobs:
```
- name: build-generator
  plan:
  - get: release-btmn-generator
    trigger: true
    passed: [test-generator]
  - task: extract-release
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: dckrreg.xxxxx/phx/base-php

      inputs:
        - name: release-btmn-generator

      outputs:
        - name: release-extract-btmn-generator
          path: extract

      run:
        dir: release-btmn-generator
        path: sh
        args:
        - -exc
        - |
          tar xzf release-*.tgz -C ../extract
  - put: docker-image-btmn-generator
    params:
      build: release-extract-btmn-generator
      build_args:
        http_proxy: {{proxy_server}}
        https_proxy: {{proxy_server}}

- name: call-generator
  plan:
  - get: docker-image-btmn-generator
    trigger: true
    passed: [build-generator]
  - get: version-btmn-generator
    passed: [build-generator]
  - task: generate-mock-data
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: dckrreg.xxxx/phx/btmn-generator

      outputs:
        - name: mock-data-btmn-generator
          path: extract

      run:
        path: sh
        args:
        - -exc
        - |
          ls -al /app
          /app/bin/console battman:build-mock-data
          tar czf extract/mock-data-`cat ../version-btmn-generator/number`.tgz /app/var/mockdata
  - put: mock-data-btmn-generator
    params:
      file: mock-data-btmn-generator/mock-data-*.tgz
```

Ressources:
```
- name: docker-image-btmn-generator
  type: docker-image
  source:
    repository: dckrreg.xxxxx:443/phx/btmn-generator
    registry_mirror: http://docker-registry-proxy.xxxxx
```

The Job: generate-data cannot be started manually. It just hangs with:
![image](https://cloud.githubusercontent.com/assets/439128/22832068/dfc77be4-efac-11e6-8336-c203696bfec1.png)
