### ISSUE TITLE
Support for pushing multiple tags other than 'latest'

### ISSUE THREAD

**Issue by dackroyd** [concourse/docker-image-resource#98]
I am looking to build and push docker images into multiple tags, none of which are 'latest'. This is to be able to push tags like `onbuild` and `onbuild-${githash}`, and then be able to use these by either taking the latest `onbuild`, or pinning the version by using the hash.

With regular images, I'm able to push both `latest` and `${githash}` tags from the same build thanks to `tag_as_latest`, but this is not possible when not using the `latest` tag for one of those (without building twice)

**Comment by dackroyd** [comment]
I have since worked around this by adding a subsequent job in the pipeline which loads the previously pushed image then pushes it with a different tag:

```
- name: build
  plan:
  - get: repo
    trigger: true
  - task: write-tag-files
     ... generate tag files ...
  - put: docker-repo
    params:
      build: repo
      dockerfile: repo/Dockerfile
      tag: tags/onbuild-version

- name: push-other-tags
  plan:
  - aggregate:
      - get: repo
        passed: [build]
        trigger: true
      - get: docker-repo
        passed: [build]
        params: {save: true}
  - task: write-tag-files
     ... generate tag files again (since I didn't push the files anywhere) ...
  - put: docker-repo
    params:
      load: docker-repo
      tag: tags/onbuild
```
